### ISSUE TITLE
About rev complementing ref and query alleles in dnadiff

### ISSUE THREAD

**Issue by leoisl** [iqbal-lab-org/varifier#10]
This part of the code rev complements both ref and query allele if the variant is reverse:
https://github.com/iqbal-lab-org/varifier/blob/82b100c95f5a6aa6522c450e965c3e1fb8c43177/varifier/dnadiff.py#L45-L51

However, note that a variant being reverse means that only the **query** allele is reverse:

https://github.com/sanger-pathogens/pymummer/blob/fd97bccfbae62719a7247473d73dd6733d4fa903/pymummer/snp.py#L21

Indeed, we don't need to check if the ref allele is reversed or not, mummer/dnadiff always outputs variants such that the ref allele is in the positive strand. The query allele can be reversed though, and in this case `pymummer` actually stores this information in the `reverse` field. My doubt is: do we actually need to rev comp also the ref allele, even though only the query allele is reversed? There might be tests checking this and all, so this issue might not actually be an issue

**Comment by leoisl** [comment]
e.g. this is one of dnadiff SNPs:
```
$ head 00.dnadiff.vcf.tmp.snps
345     A       G       1060    21      345     4824417 4905296 1       -1      0       0
```
The 9th column says that the ref strand is `+` (as always), but the 10th column says that the query strand is `-`.

And this is the record in the VCF (note both bases are RC-ed):
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
0       345     .       T       C       .       .       QNAME=0;QSTART=4904237;QSTRAND=+;SVTYPE=DNADIFF_SNP    GT      1/1
```

**Comment by martinghunt** [comment]
Note sure if you're saying this is a bug or not? The test for making the truth VCF is here:
https://github.com/iqbal-lab-org/varifier/blob/master/tests/dnadiff_test.py#L11

It runs `dnadiff.make_truth_vcf()` twice. Same ref genome both times, but the truth genome is reverse complemented in the second run. The test checks for the same expected output VCF in both cases.

**Comment by leoisl** [comment]
This is all fine, my bad
