### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mbhall88** [iqbal-lab-org/varifier#27]
Is the tip of master stable? If so, could you please create a new release? Keen to incorporate the new fixes into my pipelines.

**Comment by martinghunt** [comment]
It's stable AFAIK, but there's a chance things may change after another round of debugging next week. I'm ok with a new release now, bearing in mind there may be another one very soon, or wait? I don't mind either way.

**Comment by mbhall88** [comment]
Both?

**Comment by martinghunt** [comment]
okey dokey. Just made release v0.3.0 from tip of master.

**Comment by mbhall88** [comment]
Ah, bioconda is linked to the PyPI package, so it isn't until there's a new PyPI release that a new bioconda version will be triggered...

**Comment by martinghunt** [comment]
... and of course I forgot to version bump in the code as well. Will make another one and send to pypi

**Comment by martinghunt** [comment]
done
